DOTNET_CuoiKy/Models/DB/Sanpham.cs
using System;
using System.Collections.Generic;

namespace DOTNET_CuoiKy.Models.DB
{
    public partial class Sanpham
    {
        public Sanpham()
        {
            Carts = new HashSet<Carts>();
            Chitiethd = new HashSet<Chitiethd>();
        }

        public int IdsanPham { get; set; }
        public string TenSp { get; set; }
        public float? GiaSp { get; set; }
        public string Hinh1 { get; set; }
        public string Hinh2 { get; set; }
        public string Hinh3 { get; set; }
        public string Hinh4 { get; set; }
        public string MoTa { get; set; }
        public int? DanhMuc { get; set; }

        public virtual Danhmuc DanhMucNavigation { get; set; }
        public virtual ICollection<Carts> Carts { get; set; }
        public virtual ICollection<Chitiethd> Chitiethd { get; set; }
    }
}

DOTNET_CuoiKy/Models/Sanpham.cs
using System;
using System.Collections.Generic;

namespace DOTNET_CuoiKy.Models
{
    public partial class Sanpham
    {
        public Sanpham()
        {
            Chitiethd = new HashSet<Chitiethd>();
        }

        public int IdsanPham { get; set; }
        public string TenSp { get; set; }
        public float? GiaSp { get; set; }
        public string Hinh1 { get; set; }
        public string Hinh2 { get; set; }
        public string Hinh3 { get; set; }
        public string Hinh4 { get; set; }
        public string MoTa { get; set; }
        public int? DanhMuc { get; set; }

        public virtual Danhmuc DanhMucNavigation { get; set; }
        public virtual ICollection<Chitiethd> Chitiethd { get; set; }
    }
}

DOTNET_CuoiKy/Areas/Admin/Controllers/SanphamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DOTNET_CuoiKy.Models.DB;
using MySql.Data.MySqlClient;
using System.Threading;
using Microsoft.AspNetCore.Authorization;
using System.IO;

namespace DOTNET_CuoiKy.Areas.admin.Controllers
{
    [Area("Admin")]
    [Authorize(AuthenticationSchemes = "Admin")]
    public class SanphamsController : Controller
    {
        private readonly comdatabaseContext _context;
       // private List<Sanpham> spLst=null;
        public SanphamsController(comdatabaseContext context)
        {
            _context = context;
        }
        private IQueryable<Sanpham> GetSanphams()
        {
            bool success = false;
            int retryCount = 0;
            MySqlException exception = null;
            while (!success && retryCount <= 6)
            {
                try
                {
                   var spLst = _context.Sanpham.Include(s => s.DanhMucNavigation);
                    success = true;
                    retryCount = 5;
                }
                catch (MySqlException e)
                {
                    exception = e;
                    success = false;
                    retryCount++;
                    Thread.Sleep(800);
                }
            }
            if (retryCount > 5)
            {
                throw exception;
            }
            return _context.Sanpham.Include(s => s.DanhMucNavigation);
        }

        // GET: admin/Sanphams
        public async Task<IActionResult> Index()
        {
            bool isAjaxCall = Request.Headers["x-requested-with"] == "XMLHttpRequest";
            var comdatabaseContext = _context.Sanpham.Include(s => s.DanhMucNavigation);
            //var comdatabaseContext = GetSanphams();
            //if (isAjaxCall)
            //{
            //    //return Json(await comdatabaseContext.ToListAsync());
            //    return new JsonResult(await comdatabaseContext.ToListAsync());
            //}
            return View( await comdatabaseContext.ToListAsync());
        }

        // GET: admin/Sanphams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanpham = await _context.Sanpham
                .Include(s => s.DanhMucNavigation)
                .FirstOrDefaultAsync(m => m.IdsanPham == id);
            if (sanpham == null)
            {
                return NotFound();
            }

            return View(sanpham);
        }

        // GET: admin/Sanphams/Create
        public IActionResult Create()
        {
            ViewData["DanhMuc"] = new SelectList(_context.Danhmuc, "IddanhMuc", "IddanhMuc");
            return View();
        }

        // POST: admin/Sanphams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdsanPham,TenSp,GiaSp,MoTa,DanhMuc")] Sanpham sanpham)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sanpham);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DanhMuc"] = new SelectList(_context.Danhmuc, "IddanhMuc", "IddanhMuc", sanpham.DanhMuc);
            return View(sanpham);
        }

        // GET: admin/Sanphams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanpham = await _context.Sanpham.FindAsync(id);
            if (sanpham == null)
            {
                return NotFound();
            }
            ViewData["DanhMuc"] = new SelectList(_context.Danhmuc, "IddanhMuc", "IddanhMuc", sanpham.DanhMuc);
            return View(sanpham);
        }

        // POST: admin/Sanphams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdsanPham,TenSp,GiaSp,MoTa,DanhMuc")] Sanpham sanpham)
        {
            if (id != sanpham.IdsanPham)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sanpham);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SanphamExists(sanpham.IdsanPham))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DanhMuc"] = new SelectList(_context.Danhmuc, "IddanhMuc", "IddanhMuc", sanpham.DanhMuc);
            return View(sanpham);
        }

        private void deleteImages(Sanpham sp)
        {
            if (!string.IsNullOrWhiteSpace(sp.Hinh1))
            {
                var oldpath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", sp.Hinh1);
                if (System.IO.File.Exists(oldpath))
                {
                    System.IO.File.Delete(oldpath);
                }
            }
            if (!string.IsNullOrWhiteSpace(sp.Hinh2))
            {
                var oldpath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", sp.Hinh2);
                if (System.IO.File.Exists(oldpath))
                {
                    System.IO.File.Delete(oldpath);
                }
            }
            if (!string.IsNullOrWhiteSpace(sp.Hinh3))
            {
                var oldpath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", sp.Hinh3);
                if (System.IO.File.Exists(oldpath))
                {
                    System.IO.File.Delete(oldpath);
                }
            }
            if (!string.IsNullOrWhiteSpace(sp.Hinh4))
            {
                var oldpath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", sp.Hinh4);
                if (System.IO.File.Exists(oldpath))
                {
                    System.IO.File.Delete(oldpath);
                }
            }
        }


        // POST: admin/Sanphams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string itemId)
        {
            var sanpham = await _context.Sanpham.FindAsync(int.Parse(itemId));
            if (sanpham != null)
            {
                List<Carts> cart = await _context.Carts.Where(sp => sp.SpId == sanpham.IdsanPham).ToListAsync();
                List<Chitiethd> CTHD = await _context.Chitiethd.Where(sp => sp.IdSp == sanpham.IdsanPham).ToListAsync();
                string tenSp = sanpham.TenSp;
                if (cart.Count() > 0)
                {
                    _context.Carts.RemoveRange(cart);
                }
                if (CTHD.Count() > 0)
                {
                    _context.Chitiethd.RemoveRange(CTHD);
                }
                _context.Sanpham.Remove(sanpham);
                deleteImages(sanpham);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                var newspLSt = _context.Sanpham.Include(dm => dm.DanhMucNavigation);
                return Ok("Xóa sản phẩm "+tenSp+ " được rồi nè dân chơi !!!");
            }
            return NotFound("Không xóa được rồi, kiếm không ra");
          
        }

        private bool SanphamExists(int id)
        {
            return _context.Sanpham.Any(e => e.IdsanPham == id);
        }
    }
}

DOTNET_CuoiKy/Areas/Admin/Views/Sanphams/Create.cshtml
@model DOTNET_CuoiKy.Models.DB.Sanpham

@{
    ViewData["Title"] = "TẠO SẢN PHẨM";
    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
}

<h1>THÊM SẢN PHẨM MỚI</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenSp" class="control-label"></label>
                <input asp-for="TenSp" class="form-control" />
                <span asp-validation-for="TenSp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiaSp" class="control-label"></label>
                <input asp-for="GiaSp" class="form-control" />
                <span asp-validation-for="GiaSp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MoTa" class="control-label"></label>
                <input asp-for="MoTa" class="form-control" />
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DanhMuc" class="control-label"></label>
                <select asp-for="DanhMuc" class="form-control" asp-items="ViewBag.DanhMuc"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DOTNET_CuoiKy/Areas/Admin/Views/Sanphams/Details.cshtml
@model DOTNET_CuoiKy.Models.DB.Sanpham

@{
    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

    ViewData["Title"] = "Chi tiết sản phẩm " + @Model.TenSp;
}

<h1>Chi tiết sản phẩm @Model.TenSp</h1>

<div>
    <h4>Sanpham</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TenSp)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TenSp)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GiaSp)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GiaSp)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hinh1)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hinh1)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hinh2)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hinh2)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hinh3)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hinh3)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hinh4)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hinh4)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MoTa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DanhMucNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DanhMucNavigation.IddanhMuc)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdsanPham">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DOTNET_CuoiKy/Areas/Admin/Views/Sanphams/Edit.cshtml
@model DOTNET_CuoiKy.Models.DB.Sanpham

@{
    ViewData["Title"] = "Edit";
    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
}

@section UploadModal{
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
    {
        @Html.AntiForgeryToken()
    }
    <div class="modal fade" id="meomeo" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="modalLabel">Upload Hình</h4>
                </div>
                <div class="modal-body" id="update-message">
                    <form id="uploadForm" method="post" enctype="multipart/form-data" action="/Uploadimage/Upload">
                        <input type="hidden" name="idSP" class="idContainer form-control" />
                        <input type="hidden" name="vitriHinh" class="imgPOS form-control" />
                        <input name="images" type="file" class="form-control" />
                        <input type="submit" value="Up Hình" class="btn btn-default" />
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}

@section UploadIMGScripts
{
    <script type="text/javascript">
        var uploadSuccess = false;
        $("#uploadForm").submit(function (event) {
            var formData = new FormData();
            formData.append("images", $('[name="images"]')[0].files[0]);
            formData.append("idSP", $('[name="idSP"]').val());
            formData.append("vitriHinh", $('[name="vitriHinh"]').val());
            event.stopPropagation();
            event.preventDefault();
            $.ajax({
                url: $(this).attr("action"),
                data: formData,
                processData: false,
                contentType: false,
                type: 'POST',
                success: function (data) {
                    console.log(data)
                    $('#update-message').text(data);
                    uploadSuccess = true;
                }
            });
            return false;
        });


        $('#meomeo').on('hidden.bs.modal', function (e) {
            if (uploadSuccess) {
                window.location.reload(true);
            } else {
                console.log("Hidden")
                //Clean old id to make sure shit wont break  !!!!!
                $("input[name=idSP]").val("");
                $("input[name=vitriHinh]").val("");
            }
        })

        $(function () {
            $('.uploadIMG').on('click', function () {
                var idSP = $(this).attr('id');
                var thuTuHinh = $(this).attr('data-id');
                $("input[name=idSP]").val(idSP);
                $("input[name=vitriHinh]").val(thuTuHinh);
                $('#meomeo').modal('show');
            })

        })

    </script>
}
<div class="container">
    <h1>Edit</h1>

    <h4>Sanpham</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="IdsanPham" />
                <div class="form-group">
                    <label asp-for="TenSp" class="control-label"></label>
                    <input asp-for="TenSp" class="form-control" />
                    <span asp-validation-for="TenSp" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="GiaSp" class="control-label"></label>
                    <input asp-for="GiaSp" class="form-control" />
                    <span asp-validation-for="GiaSp" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MoTa" class="control-label"></label>
                    <input asp-for="MoTa" class="form-control" />
                    <span asp-validation-for="MoTa" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DanhMuc" class="control-label"></label>
                    <select asp-for="DanhMuc" class="form-control" asp-items="ViewBag.DanhMuc"></select>
                    <span asp-validation-for="DanhMuc" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Lưu thông tin" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group" action="myform.cgi">
                <label asp-for="Hinh1" class="control-label"></label>
                <img src="~/@Model.Hinh1" id="Hinh1" />
                <button data-id="1" id="@Model.IdsanPham" class="btn btn-success uploadIMG">Chỉnh sửa hình ảnh</button>
            </div>
            <div class="form-group">
                <label asp-for="Hinh2" class="control-label"></label>
                <img src="~/@Model.Hinh2" id="Hinh2" />
                <button data-id="2" id="@Model.IdsanPham" class="btn btn-success uploadIMG">Chỉnh sửa hình ảnh</button>

            </div>
            <div class="form-group">
                <label asp-for="Hinh3" class="control-label"></label>
                <img src="~/@Model.Hinh3" id="Hinh3" />
                <button data-id="3" id="@Model.IdsanPham" class="btn btn-success uploadIMG">Chỉnh sửa hình ảnh</button>
            </div>
            <div class="form-group">
                <label asp-for="Hinh4" class="control-label"></label>
                <img src="~/@Model.Hinh4" id="Hinh4" />
                <button data-id="4" id="@Model.IdsanPham" class="btn btn-success uploadIMG">Chỉnh sửa hình ảnh</button>

            </div>
        </div>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

DOTNET_CuoiKy/Areas/Admin/Views/Sanphams/Index.cshtml
@model IEnumerable<DOTNET_CuoiKy.Models.DB.Sanpham>

@{
    ViewData["Title"] = "Danh sách sản phẩm";
    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
}

@section style{
    <style>
        .Fcapital {
            text-transform: capitalize;
        }
    </style>
}

@section warningModal{
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
    {
        @Html.AntiForgeryToken()
    }
    <div class="modal fade" id="flipFlop" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="modalLabel">Cảnh báo</h4>
                </div>
                <div class="modal-body" id="update-message">

                </div>
                <div class="modal-footer">
                    <a class="btn btn-danger deleteConfirm">XÁC NHẬN XÓA </a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}

@section script{

    <script type="text/javascript">
        $(function () {
            var deleteSuccess = false;
            // Make sure everything is reset after modal closed
            $('#flipFlop').on('hidden.bs.modal', function (e) {
                if (deleteSuccess) {
                    window.location.reload();
                } else {
                    console.log("Hidden")
                    //Clean old id to make sure shit wont break  !!!!!
                    $('#update-message').text(null);
                    var confirmBnt = document.getElementsByClassName("deleteConfirm")[0];
                    confirmBnt.id = "";
                    confirmBnt.style = "";
                }
            })

            // Document.ready -> link up remove event handler
            //Show warning modal
            $(".deleteShit").click(function () {
                var confirmBnt = document.getElementsByClassName("deleteConfirm")[0];
                var itemName = $(this).attr("data-id").toLocaleUpperCase();
                // Set id to confirm modal button so we can delete more ez
                confirmBnt.id = $(this).attr("id");;
                $('#update-message').text("Bạn có chắc muốn xóa sản phẩm " + itemName);
                $('#flipFlop').modal('show');
            });
            //Confirm delete
            $(".deleteConfirm").click(function () {
                $('#update-message').text("Đang gửi dữ liệu để xóa xin chờ....");
                $('.deleteConfirm').hide();
                var form = $('#__AjaxAntiForgeryForm');
                var token = $('input[name="__RequestVerificationToken"]', form).val();
                var iditem = $(this).attr("id");
                if (iditem != '') {
                    $.post("/admin/Sanphams/Delete", { __RequestVerificationToken: token, "itemId": iditem },
                        function (data) {
                            console.log('server response', JSON.stringify(data))
                            deleteSuccess = true;
                            $('#update-message').text(data);
                        }).fail(function (data) {
                            //console.log('server response', JSON.stringify(data.responseText))
                            $('#update-message').text(data.responseText);
                        })
                }
            });

        });
    </script>
}
<h2>Danh sách sản phẩm của bạn</h2>

<div class="text-warning">
    @ViewBag.ProError
</div>
<hr />

<p>
    <a asp-action="Create">Tạo món ăn mới</a>
</p>
<table id="SanPhamLST" class="table">
    <thead>
        <tr>
            <th>
                Tên món ăn
            </th>
            <th>
                Giá
            </th>
            <th>
                Danh mục của sản phẩm
            </th>
            <th>
                Tùy chọn
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @*@Html.DisplayFor(modelItem => item.TenSp)*@
                    @Html.ActionLink(item.TenSp, "Details", "Sanphams", new { id = item.IdsanPham }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GiaSp)
                </td>

                <td>
                    <span class="Fcapital">
                        @Html.DisplayFor(modelItem => item.DanhMucNavigation.TenDm)
                    </span>
                </td>
                <td>
                    <a class="btn btn-sm btn-info" asp-action="Edit" asp-route-id="@item.IdsanPham">Sửa thông tin</a> |

                    <a class="deleteShit btn btn-sm btn-danger" data-id="@item.TenSp" id="@item.IdsanPham" @*asp-action="Delete" asp-route-id="@item.IdsanPham" *@>Xóa Sản phẩm này</a>
                </td>
            </tr>
        }
    </tbody>
</table>